### ISSUE TITLE
[FEAT] Read the protocol ID from the config 

### ISSUE THREAD

**Issue by iulianpascalau** [ElrondNetwork/elrond-eth-bridge#27]
Should read the protocol ID value from config instead of using a hardcoded value:
https://github.com/ElrondNetwork/elrond-eth-bridge/blob/68f8f6640d6da7459c6b46c7a25f5acb81d36eb5/relay/relay.go#L357

**Comment by alexandru-calinoiu** [comment]
Fixed here https://github.com/ElrondNetwork/elrond-eth-bridge/pull/47
