### ISSUE TITLE
[FEAT] Use gas cost from elrond docs

### ISSUE THREAD

**Issue by alexandru-calinoiu** [ElrondNetwork/elrond-eth-bridge#29]
Right now the gas cost value is hardcoded to a very large number, 

Ideally the gas should be estimated using an sdk function `RequestTransactionCost`

An alternate solution will be to use the gas estimates from here https://github.com/ElrondNetwork/sc-bridge-elrond/blob/main/docs/gas_costs.md

**Comment by alexandru-calinoiu** [comment]
Add 10 mil buffer

**Comment by sasurobert** [comment]
Use the alternate solution - there is no need to recalculate gas for every transfer, when we know those preemptively:
An alternate solution will be to use the gas estimates from here https://github.com/ElrondNetwork/sc-bridge-elrond/blob/main/docs/gas_costs.md

**Comment by alexandru-calinoiu** [comment]
fIxed
