### ISSUE TITLE
[BUG] Nonce too low

### ISSUE THREAD

**Issue by mihaib79** [ElrondNetwork/elrond-eth-bridge#30]
In the actual implementation, the Client has a nonce function field, that retrieves the nonce from the proxy, everytime it is needed. Since the nonce is updated only one time per round, issues arise when more transactions are sent during the same round.
In order to avoid this, I would define the Client's nonce as a regular uint64 value, and initialize it during the NewClient function.
Each time we send a transaction, we would just increment the nonce.
Then I would launch a go routine that synchronizes the nonce with the network once per minute.
The interval can be even 5 minutes or more, since the relayer's owner is not supposed to use the relayer's wallet to make transactions.

**Comment by alexandru-calinoiu** [comment]
The solution you describe sounds a little brittle, I suppose we can do it if there is no other way around it.

Is there any other way to find the round the transaction was into?

If there was one can simply check if this is new round and get the new nonce.

**Comment by alexandru-calinoiu** [comment]
Issue was fixed here https://github.com/ElrondNetwork/elrond-eth-bridge/pull/35
