### ISSUE TITLE
[BUG] NewRelay is not setting the elrondPublicAddress base on the PEM file

### ISSUE THREAD

**Issue by mihaieremia** [ElrondNetwork/elrond-eth-bridge#36]
The new relay is not assigning the elrondPublicAddress for the instance and we cannot broadcast the join messages, also we cannot check if the relayer IsWhitelisted.

**Comment by alexandru-calinoiu** [comment]
Fixed here https://github.com/ElrondNetwork/elrond-eth-bridge/pull/37
