### ISSUE TITLE
[FEAT] Get the GasLimit from config and not from a hardcoded constant

### ISSUE THREAD

**Issue by mihaieremia** [ElrondNetwork/elrond-eth-bridge#45]
We should move out the ETH GasLimit from the go code to the config file.

**Comment by alexandru-calinoiu** [comment]
Not sure if this is the right approach, most likely the gas limit might need to get calculated dynamically based on the number of tx's

**Comment by sasurobert** [comment]
Is it so hard to make a function which increases somewhat linearly to the number of token transfera which has to be done? Common. White are we waiting. 2 lines of code.

**Comment by alexandru-calinoiu** [comment]
Actually I take that back, is hard to estimate the gas limit, the best way is to get them from the estmate in the tests

<img width="1303" alt="Screenshot 2021-09-24 at 08 32 23" src="https://user-images.githubusercontent.com/679198/134623634-bdb6a5bb-f412-45ee-9c33-eecdd32477c4.png">

**Comment by levelboy** [comment]
I think it is reasonable to set the gas limit to the highest possible gas consumption based on our test scenarios. It doesn't need to scale with the number of transactions in the batch. 

Just for clarification, the gas limit set there, doesn't mean that we will send x Gwei on each transaction. All gas that will be not consumed, will be returned to the sender of the transaction.

**Comment by alexandru-calinoiu** [comment]
fixed
