### ISSUE TITLE
[FEAT] Relayers should send EIP-1559 transactions

### ISSUE THREAD

**Issue by levelboy** [ElrondNetwork/elrond-eth-bridge#51]
Relayers are sending Legacy Transactions (e.g. https://ropsten.etherscan.io/tx/0xa6d1b0c47d8e3d82cc84214dff5ddcddefa77428bd519f6f4fd56e296f54ece6)

For better gas price estimates and predictability for transactions to be executed quickly, we should use the EIP-1559 version of transactions.

Go Ethereum library should already implement EIP-1559.

**Comment by alexandru-calinoiu** [comment]
Fixed here https://github.com/ElrondNetwork/elrond-eth-bridge/pull/54/commits/9b52c4be99a2f758738f4af7b7ed448f051e762c
