### ISSUE TITLE
Typo when deploying Bridge contract

### ISSUE THREAD

**Issue by cleanunicorn** [ElrondNetwork/elrond-eth-bridge#56]
A typo exists in the argument list when deploying the Bridge.

https://github.com/ElrondNetwork/elrond-eth-bridge/blob/437947a0c447b80f78f578bd5fb0f13b74c6fcde/contracts/ethereum-sc/contracts/Bridge.sol#L57

It should be `initialQuorum`.

**Comment by ccorcoveanu** [comment]
Will close the issue since this has been solved in the new repo, see here: https://github.com/ElrondNetwork/sc-bridge-ethereum-sol/blob/main/contracts/Bridge.sol#L50
