### ISSUE TITLE
Check initial quorum is at least the size of the board

### ISSUE THREAD

**Issue by cleanunicorn** [ElrondNetwork/elrond-eth-bridge#58]
For sanity, the `initialQuorum` should be equal to or less than the current board size.

This is easier to check when initially setting the board members, on deploy.

https://github.com/ElrondNetwork/elrond-eth-bridge/blob/437947a0c447b80f78f578bd5fb0f13b74c6fcde/contracts/ethereum-sc/contracts/Bridge.sol#L55-L74

An additional check can be done similar to the example below:

```solidity
require(board.length >= initialQuorum, "The board should be at least the quorum size.");
```

Even though it doesn't block the whole contract (more board members can be added later), it ensures the full functionality of the contract if enough are added from the beginning.

Later in the contract, the size of the board is "lost" because adding and removing members does not update a board size. Consider updating the board size when adding and removing board members.

https://github.com/ElrondNetwork/elrond-eth-bridge/blob/437947a0c447b80f78f578bd5fb0f13b74c6fcde/contracts/ethereum-sc/contracts/Bridge.sol#L76-L80

https://github.com/ElrondNetwork/elrond-eth-bridge/blob/437947a0c447b80f78f578bd5fb0f13b74c6fcde/contracts/ethereum-sc/contracts/Bridge.sol#L93-L97

The size of the board is useful when setting the quorum size to ensure proper functionality of the whole system. The updated size could be checked against the new proposed quorum size:

https://github.com/ElrondNetwork/elrond-eth-bridge/blob/main/contracts/ethereum-sc/contracts/Bridge.sol#L106-L114

**Comment by ccorcoveanu** [comment]
I also believe that it would be transparent to always know the board. We currently don't have an option for listing board members - or board size as you mentioned.
Do you think it would be useful to have the list in the storage?

And from what I know, the check for the quorum to be `<= board.length` is missing because it can be a "feature" to temporary block execution. But that in my opinion should be done differently by pausing. It's cleaner and you always know why transfers aren't being completed.

**Comment by dekuyper** [comment]
> I also believe that it would be transparent to always know the board. We currently don't have an option for listing board members - or board size as you mentioned. Do you think it would be useful to have the list in the storage?

I agree, at the moment the board is set in a mapping on the AccessControl contract with no way of iterating through it.
One solution would be to clone the openzeppelin AccessControl and add:
```
    struct RoleData {
        mapping(address => bool) members;
        bytes32 adminRole;
        address[] memberList;
    }
...
    function getRoleMembers(bytes32 role) public view returns (address[] memory) {
        return _roles[role].memberList;
    }

```
This could also address the issues where starting with v4.1, the **@openzeppelin/contracts** package is using a different revert reason, which would make the tests fail by not using these libraries/contracts. Also decrease deployment costs.
```
import "../utils/Context.sol";
import "../utils/Strings.sol";
```

> And from what I know, the check for the quorum to be `<= board.length` is missing because it can be a "feature" to temporary block execution. But that in my opinion should be done differently by pausing. It's cleaner and you always know why transfers aren't being completed.

Pausing should be preferred.
