### ISSUE TITLE
Anyone can add or remove relayers

### ISSUE THREAD

**Issue by cleanunicorn** [ElrondNetwork/elrond-eth-bridge#59]
Anyone can add a new relayer, possibly adding enough to execute any action they want.

https://github.com/ElrondNetwork/elrond-eth-bridge/blob/437947a0c447b80f78f578bd5fb0f13b74c6fcde/contracts/ethereum-sc/contracts/Bridge.sol#L76-L91

Should be restricted to some members, i.e., adding `onlyAdmin` to both methods.

```solidity
function addRelayer(address newRelayerAddress) external onlyAdmin {
```

```solidity
function removeRelayer(address relayerAddress) external onlyAdmin {
```

**Comment by levelboy** [comment]
grantRole is restricted to admin only. This is AccessControl functionality.

**Comment by levelboy** [comment]
https://github.com/ElrondNetwork/elrond-eth-bridge/blob/437947a0c447b80f78f578bd5fb0f13b74c6fcde/contracts/ethereum-sc/contracts/Bridge.sol#L89

**Comment by levelboy** [comment]
There's also a test for this: https://github.com/ElrondNetwork/elrond-eth-bridge/blob/437947a0c447b80f78f578bd5fb0f13b74c6fcde/contracts/ethereum-sc/test/Bridge-test.js#L86

**Comment by cleanunicorn** [comment]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1b27c13096d6e4389d62e7b0766a1db53fbb3f1b/contracts/access/AccessControl.sol#L119-L131
