### ISSUE TITLE
ERC20Safe deposit check if last batch is oversized or expired

### ISSUE THREAD

**Issue by dekuyper** [ElrondNetwork/elrond-eth-bridge#65]
In **ERC20Safe.deposit** the first `if` statement is trying to decide whether to create a new batch or add to the old batch deposits. 

https://github.com/ElrondNetwork/elrond-eth-bridge/blob/ddec27fe6b3755651803b659a779f4f509ef4064/contracts/ethereum-sc/contracts/ERC20Safe.sol#L115-L125

The verification `batches[batchesCount - 1].timestamp + batchTimeLimit < currentTimestamp` will evaluate to `false` if the last batch has an expired time limit and it will proceed to evaluate the third `or` statement which checks whether the last batch has more deposits then the configured batch size.

| timestamp + batchTimeLimit < currentTimestamp (not expired) | deposits.length >= batchSize (oversized) | new batch |
| ----------------------------------------------------------- | ---------------------------------------- | --------- |
| 1                                                           | 0                                        | 1         |
| 1                                                           | 1                                        | 1         |
| 0                                                           | 1                                        | 1         |
| 0                                                           | 0                                        | 0         |

By negating the first column we get the following result:

| expired | over batch size | new batch |
| ------- | --------------- | --------- |
| 0       | 0               | 1         |
| 0       | 1               | 1         |
| 1       | 1               | 1         |
| 1       | 0               | 0         |

This in effect causes 2 problems:

- First row: the deposit goes in a new batch even though the last batch is neither expired nor oversized
- Last row: adds a new deposit in the last batch even if it's oversized

**Comment by levelboy** [comment]
Started to write a test for this, and I couldn't make it to fail. 
Looking into more detail on this, the first assumption seems wrong:
`batches[batchesCount - 1].timestamp + batchTimeLimit < currentTimestamp` evaluates to `true` when the current (last) batch is expired.
e.g.
We create a new batch at midnight: `batchTimestamp = 00:00`
`batchTimeLimit` is 10 minutes (600 seconds) 

With these, `batchExpirationTimestamp = batchTimestamp + batchTimeLimit` so this makes the batch active until 00:10

There is one deposit coming every three minutes.

00:03 evaluates the following expression:
    00:10 (`batchExpirationTimestamp`) < 00:03 (`currentTimestamp`) 
        -> false
            -> evaluates next expression


00:06 evaluates the following expression:
    00:10 (`batchExpirationTimestamp`) < 00:06 (`currentTimestamp`) 
        -> false
            -> evaluates next expression

00:09 evaluates the following expression:
    00:10 (`batchExpirationTimestamp`) < 00:09 (`currentTimestamp`) 
        -> false
            -> evaluates next expression

00:12 evaluates the following expression:
    00:10 (`batchExpirationTimestamp`) < 00:12 (`currentTimestamp`) 
        -> true
            -> creates a new batch


There is a scenario though, where it does evaluate false right on the second that it expires
e.g. 
a deposit coming in at 00:10 evaluates the following expression:
    00:10 (`batchExpirationTimestamp`) < 00:10 (`currentTimestamp`) 
        -> false
            -> evaluates next expression

**Comment by dekuyper** [comment]
With the assumption that `batch.timestamp + batchTimeLimit < currentTimestamp` -> **not expired** it's not a bug indeed.
Closing.
